"tagFormat": "${version}"

"branches":
  - "master"

"plugins":
  # Analyzes commits to identify the type of update (ex.: fix -> PATCH, feat -> MINOR...)
  - "@semantic-release/commit-analyzer"

  # Generates the changelog text and creates a CHANGELOG file at each release
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"

  # Publish on GitHub
  - - "@semantic-release/github"
    - "assets":
      - "path": "chess/build/libs/chess.jar"
        "label": "Executable fat JAR"
